version: "3.3"

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: otel
    ports:
      - "5432:5432"
    restart: always
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=info
    ports:
      - "16686:16686"
      - "14268:14268"
    restart: always