DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR (64) NOT NULL,
    username VARCHAR (32) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (email)
);

DROP TABLE IF EXISTS emails;
CREATE TABLE emails (
	id SERIAL PRIMARY KEY,
	email VARCHAR (64) NOT NULL,
	subject VARCHAR (64) NOT NULL,
	body TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- create a table attachments
DROP TABLE IF EXISTS attachments;
CREATE TABLE attachments (
	id SERIAL PRIMARY KEY,
	email INTEGER NOT NULL,
	attachment TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)