// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proto/stored/v1/stored.proto

package stored

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StoredServiceClient is the client API for StoredService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoredServiceClient interface {
}

type storedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoredServiceClient(cc grpc.ClientConnInterface) StoredServiceClient {
	return &storedServiceClient{cc}
}

// StoredServiceServer is the server API for StoredService service.
// All implementations should embed UnimplementedStoredServiceServer
// for forward compatibility
type StoredServiceServer interface {
}

// UnimplementedStoredServiceServer should be embedded to have forward compatible implementations.
type UnimplementedStoredServiceServer struct {
}

// UnsafeStoredServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoredServiceServer will
// result in compilation errors.
type UnsafeStoredServiceServer interface {
	mustEmbedUnimplementedStoredServiceServer()
}

func RegisterStoredServiceServer(s grpc.ServiceRegistrar, srv StoredServiceServer) {
	s.RegisterService(&StoredService_ServiceDesc, srv)
}

// StoredService_ServiceDesc is the grpc.ServiceDesc for StoredService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoredService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.stored.v1.StoredService",
	HandlerType: (*StoredServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/stored/v1/stored.proto",
}
